### ISSUE TITLE
Ability to remove enchantments

### ISSUE THREAD

**Issue by Clayell** [myaltaccountsthis/arcane-odyssey-guides#15]
I think it would be nice if there was an option to completely remove enchantments altogether from the calculations, as there isn't right now.

Thanks a lot for this wonderful armor build calculator, and I hope it can be made even better!

EDITED TO REMOVE ALREADY ADDED STUFF

**Comment by Clayell** [comment]
Wow I feel like an idiot, I was looking at the wrong armor calculator and didn't realize the new one already has most of this stuff, nice! It would still be nice if there was an option to disable enchantments altogether though.

**Comment by a-fakeusername** [comment]
I added the option to remove exotic enchants and jewels. I don't think removing enchants entirely would be necessary since normal enchants are already really easy to get.

**Comment by Clayell** [comment]
> I added the option to remove exotic enchants and jewels. I don't think removing enchants entirely would be necessary since normal enchants are already really easy to get.

They're easy to get sure, but if you wanna find the stats of an armor set without any enchants then you need to do it manually. (especially for things like updating the wiki)

**Comment by myaltaccountsthis** [comment]
Definitely need enchants now
