### ISSUE TITLE
[Suggestion] This might be a surprise. Akursius Keep.

### ISSUE THREAD

**Issue by MommaDragon** [myaltaccountsthis/arcane-odyssey-guides#3]
![image](https://github.com/myaltaccountsthis/arcane-odyssey-guides/assets/106483611/88f076cd-d40c-45b8-91f0-864798040641)
There might not be many actual diggable spots, however.

**Comment by myaltaccountsthis** [comment]
Yes, there are treasures on Akursius. It's just small so I removed it from the website.

**Comment by MommaDragon** [comment]
Well, why remove it? It could still prove to be useful to some people...

**Comment by myaltaccountsthis** [comment]
Small islands take too much effort to center them properly compared to the difficulty of obtaining the treasure. Centering/resizing Ravenna is not much work compared to trying to find Ravenna treasure, but centering/resizing Akursius Keep is too much work compared to how rare Akursius treasure is and how few parts are on the island.
